/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BlockFarmInterface extends Interface {
    getFunction(nameOrSignature: "jumlahProduk" | "produkList" | "tambahProduk"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProdukDitambahkan"): EventFragment;

    encodeFunctionData(functionFragment: 'jumlahProduk', values?: undefined): string;
encodeFunctionData(functionFragment: 'produkList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tambahProduk', values: [string, string, string, string, string]): string;

    decodeFunctionResult(functionFragment: 'jumlahProduk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'produkList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tambahProduk', data: BytesLike): Result;
  }

  
    export namespace ProdukDitambahkanEvent {
      export type InputTuple = [productId: string, namaProduk: string, namaPetani: string];
      export type OutputTuple = [productId: string, namaProduk: string, namaPetani: string];
      export interface OutputObject {productId: string, namaProduk: string, namaPetani: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BlockFarm extends BaseContract {
    
    connect(runner?: ContractRunner | null): BlockFarm;
    waitForDeployment(): Promise<this>;

    interface: BlockFarmInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    jumlahProduk: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    produkList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string] & {productId: string, namaProduk: string, namaPetani: string, lokasi: string, tanggalPanen: string }],
      'view'
    >
    

    
    tambahProduk: TypedContractMethod<
      [_productId: string, _namaProduk: string, _namaPetani: string, _lokasi: string, _tanggalPanen: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'jumlahProduk'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'produkList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string] & {productId: string, namaProduk: string, namaPetani: string, lokasi: string, tanggalPanen: string }],
      'view'
    >;
getFunction(nameOrSignature: 'tambahProduk'): TypedContractMethod<
      [_productId: string, _namaProduk: string, _namaPetani: string, _lokasi: string, _tanggalPanen: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProdukDitambahkan'): TypedContractEvent<ProdukDitambahkanEvent.InputTuple, ProdukDitambahkanEvent.OutputTuple, ProdukDitambahkanEvent.OutputObject>;

    filters: {
      
      'ProdukDitambahkan(string,string,string)': TypedContractEvent<ProdukDitambahkanEvent.InputTuple, ProdukDitambahkanEvent.OutputTuple, ProdukDitambahkanEvent.OutputObject>;
      ProdukDitambahkan: TypedContractEvent<ProdukDitambahkanEvent.InputTuple, ProdukDitambahkanEvent.OutputTuple, ProdukDitambahkanEvent.OutputObject>;
    
    };
  }