/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedagangRouteImport } from './routes/pedagang'
import { Route as KonsumenRouteImport } from './routes/konsumen'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as IndexRouteImport } from './routes/index'

const PedagangRoute = PedagangRouteImport.update({
  id: '/pedagang',
  path: '/pedagang',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsumenRoute = KonsumenRouteImport.update({
  id: '/konsumen',
  path: '/konsumen',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distributor': typeof DistributorRoute
  '/explorer': typeof ExplorerRoute
  '/konsumen': typeof KonsumenRoute
  '/pedagang': typeof PedagangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distributor': typeof DistributorRoute
  '/explorer': typeof ExplorerRoute
  '/konsumen': typeof KonsumenRoute
  '/pedagang': typeof PedagangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distributor': typeof DistributorRoute
  '/explorer': typeof ExplorerRoute
  '/konsumen': typeof KonsumenRoute
  '/pedagang': typeof PedagangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/distributor' | '/explorer' | '/konsumen' | '/pedagang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/distributor' | '/explorer' | '/konsumen' | '/pedagang'
  id:
    | '__root__'
    | '/'
    | '/distributor'
    | '/explorer'
    | '/konsumen'
    | '/pedagang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributorRoute: typeof DistributorRoute
  ExplorerRoute: typeof ExplorerRoute
  KonsumenRoute: typeof KonsumenRoute
  PedagangRoute: typeof PedagangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedagang': {
      id: '/pedagang'
      path: '/pedagang'
      fullPath: '/pedagang'
      preLoaderRoute: typeof PedagangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsumen': {
      id: '/konsumen'
      path: '/konsumen'
      fullPath: '/konsumen'
      preLoaderRoute: typeof KonsumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributorRoute: DistributorRoute,
  ExplorerRoute: ExplorerRoute,
  KonsumenRoute: KonsumenRoute,
  PedagangRoute: PedagangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
